revisit SymbolFactory
(also needed for Lib, Verilog, EDD etc.)

- decouple "Paramset"
- non-const Element::find_
- Factory is an Element
- Factory+Symbol interface
- rename set_dev_type
- fix verilog::parse_type
- streamline instanciation in root

diff --git a/tests/prj_log_compiler b/tests/prj_log_compiler
--- a/tests/prj_log_compiler
+++ b/tests/prj_log_compiler
@@ -60,7 +60,10 @@ for i in $( cd ${srcdir}; ls $base/*.{sch,vs} ) ; do
 		cmd="$DIFF ${out}/${F} ${ref}/${F}"
 		eval echo "$cmd" ${REDIR}
 		eval "$cmd" ${REDIR}
-		if [ $? -ne 0 ]; then status=FAIL; fi
+		if [ $? -ne 0 ]; then
+			echo "ERROR $F"
+			status=FAIL;
+		fi
 	done
 
 done
